flowchart LR
    A[Transaction Created] --> B[Generate PDF]
    B --> C[Verification Code]
    C --> D[QR/URL Verify]
    D --> E[Simpan di Storage]
flowchart LR
    A[Transaction Created] --> B[Generate PDF]
    B --> C[Verification Code]
    C --> D[QR/URL Verify]
    D --> E[Simpan di Storage]
